### ISSUE TITLE
Stock quantity always shows 9999 when enabled

### ISSUE THREAD

**Issue by adnanalneon** [pluginever/wc-serial-numbers#135]
When serial numbers are assigned to a product and a stock quantity is set, stock quantity shows 9999 for all stock quantity chosen from the product page.

**Comment by syedladen** [comment]
The latest version 1.4.9 and 1.2.4 are now updated with the stock showing policy for the serial key sources. 

Manually added serial keys show the exact amount of stocks in the report section. Whereas, The Generator Rule and Auto Generated Serial Number only show "-" because they are the automated source for the serial keys. 

Hence the 9999 only showed for the generator rule and auto-generated serial number. But now stock only shows the manual added.

The issue is fixed.
