### ISSUE TITLE
Rename "Serial Key" to "Key"

### ISSUE THREAD

**Issue by bappi** [pluginever/wc-serial-numbers#371]
In the core plugin.

**Comment by gmn42** [comment]
Hello, I hope you don't mind a comment about this terminology from the outside, but i've noticed a couple of issues related to it.  I agree that "Serial key" is awkward and should be changed, but I'd suggest using "Numbers" instead, since your product is "Serial _Numbers_ for Woocommerce".   Unless, of course, you're planning on changing the name of the plugin too.

FYI, in american English at least, the term "serial key" is not commonly used, and is actually a bit of contradiction.  "serial", by definition, implies a _sequential_ unique number (often related to production order), while "key" implies a crpytographically strong, unpredictable identifier, which is usually called a "product" or "activation" key.  Most of your users apply it in the latter sense, although in my application I actually DO use it more in the sense of a serial number.

Again, not a criticism, but something you might not necessarily be considering.  For what it's worth, a "serial number" often does contain letters, so this in itself isn't contradictory to common usage, and thus term "number" and could apply to both types of information being tracked while still remaining true to the name of the plugin.

In any case, I appreciate that most or all of the front-end labels can be changed, so it's mostly for an issue for internal comprehension and staff training on the dashboard.

**Comment by bappi** [comment]
Hello @gmn42, 

Thanks a lot for your insights, we'll definitely discuss it and go for the most suitable term. 

May I please know the exact use case for you? I mean why and how you're using the plugin, and if you have any feedback based on your use case?

**Comment by gmn42** [comment]
Sure.  We're a small company that rents physical, natural products (you can figure out more the company name on the pro sub).  Although there are many items with the same SKU, they are not fungible, and we need to connect each order to a physical unit in our lot.  Each unit is identified by a unique number that encodes last digit of the year and lot location (e.g, 3-04-19 for 2023, row 4, slot 19), so it's not a true serial number, but in principle, the same number is never used twice.  That number is tracked in wcsn, and the main purpose is to make sure that each unit isn't sold more than once.

I've written a custom plugin that adds some functionality, like tracking the number per-line-item and allowing customers to purchase a particular item using their phone to scan a QR code; the serial number is then automatically assigned to that order.  In other cases, the customer orders online, and our staff assigns a serial number on the admin order page from a drop-down of available serial numbers.  We don't do any auto-assigning of numbers.

I did have to make some changes to the core wcsn, and I'm currently in the process of merging my branch into the current head (you've been busy over the last year or so!).  I'll go ahead and submit upstream PRs for them, in case you'd like to use them (or know a way to do it better!).

I do have some other ideas i'd like to coordinate with you on - for example, based on the code and schema, it looks like you're moving to per-line tracking of numbers, and i'd like to make sure my plugin works with that.  What's the best forum to discuss that?  Open a feature request here?

While our specific use case is fairly unusual, the idea of keeping track of unique physical products sold, where they are not unique enough justify creating separate one-time-use SKUs in WC, has wider application (e.g., a company selling high-value equipment that needs to record the machine serial number on the order.)  Even though wcsn seems to be really aimed toward managing product/activation keys rather than physical serial numbers, it's worked well enough for us with some tweaks.

**Comment by bappi** [comment]
another related pr https://github.com/pluginever/wc-serial-numbers/pull/357
